# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lorenzogrossi <lorenzogrossi@student.42    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/07 11:15:10 by mcenci            #+#    #+#              #
#    Updated: 2023/04/13 14:39:33 by lorenzogros      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
SCR = ./ft_isalpha.c ./ft_isdigit.c ./ft_isalnum.c ./ft_isascii.c ./ft_isprint.c ./ft_strlen.c ./ft_memset.c ./ft_bzero.c ./ft_memcpy.c ./ft_memmove.c ./ft_strlcpy.c ./ft_strlcat.c ./ft_toupper.c ./ft_tolower.c ./ft_strchr.c ./ft_strrchr.c ./ft_strncmp.c ./ft_memchr.c ./ft_memcmp.c ./ft_strnstr.c ./ft_atoi.c ./ft_calloc.c ./ft_strdup.c ./ft_putnbr_fd.c ./ft_putstr_fd.c ./ft_putchar_fd.c ./ft_putendl_fd.c ./ft_striteri.c ./ft_strmapi.c ./ft_substr.c ./ft_strjoin.c ./ft_strtrim.c ./ft_itoa.c ./ft_split.c
SCRB = ./ft_lstnew.c ./ft_lstadd_front.c ./ft_lstsize.c ./ft_lstlast.c ./ft_lstadd_back.c ./ft_lstdelone.c ./ft_lstclear.c ./ft_lstiter.c ./ft_lstmap.c
FLAGS = -Wall -Wextra -Werror
OBJ = $(SCR:%.c=%.o)
OBJB = $(SCRB:%.c=%.o)

all: $(NAME)
$(NAME):
		gcc -c $(FLAGS) $(SCR)
		ar rcs $(NAME) $(OBJ)
bonus :	$(OBJB)
		gcc -c $(FLAGS) $(SCRB)
		ar rcs $(NAME) $(OBJB)

clean:
		rm -f $(OBJ) $(OBJB)

fclean:	clean
		rm -f $(NAME)

re:	fclean all
